server:
  port: 9202
directAsyncConsumer:
  exchangeName: direct.exchange.async
  queueName: direct.exchange.async.queue
  routingKey: 1000
directSyncConsumer:
  exchangeName: direct.exchange.sync
  queueName: direct.exchange.sync.queue
  routingKey: 2000
spring:
  sleuth:
    baggage:
      remote-fields:
        - "requestId"
      correlation-fields:
        - "requestId"