server:
  port: 9201
directAsyncConsumer:
  exchangeName: direct.exchange.async
  routingKey: 1000
directSyncConsumer:
  exchangeName: direct.exchange.sync
  routingKey: 2000
logging:
  config: classpath:logback-spring.xml
spring:
  sleuth:
    baggage:
      remote-fields:
        - "requestId"
      correlation-fields:
        - "requestId"
