spring:
  application:
    name: producer-service
server:
  port: 9201
directAsyncConsumer:
  exchangeName: direct.exchange.async
  routingKey: 1000
directSyncConsumer:
  exchangeName: direct.exchange.sync
  routingKey: 2000